export const SEARCH_NEARBY_RESTAURANTS = 'SEARCH_NEARBY_RESTAURANTS';
export const GET_USER_FAVORITE_VENUE = 'GET_USER_FAVORITE_VENUE';
export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const SET_VENUE_AS_FAVORITE = 'SET_VENUE_AS_FAVORITE';
export const GET_VENUE_DETAILS = 'GET_VENUE_DETAILS';
