export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const SET_USER = 'SET_USER';
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';
export const SET_SORTED_RESTAURANTS = 'SET_SORTED_RESTAURANTS';
export const SET_VENUE_DETAILS = 'SET_VENUE_DETAILS';
export const RESET_VENUE_DETAILS = 'RESET_VENUE_DETAILS';
